### ISSUE TITLE
BUG: Nodal Displacements not available for Natural Vibrations

### ISSUE THREAD

**Issue by lucasepp** [karamba3d/K3D_NightlyBuilds#26]
**Description**
In previous Karamba versions, if used after a Natural Vibrations component, the Nodal Displacements component would output the unity-normalized eigenvectors.

In recent nightly builds the Nodal Displacements component now throws an error:
![image](https://user-images.githubusercontent.com/6627429/104419566-7e8d2280-552d-11eb-9c7b-b56ebcb6efc9.png)

**To Reproduce**
See attached simple .gh script.
[eigenvector extraction.zip](https://github.com/karamba3d/K3D_NightlyBuilds/files/5807019/eigenvector.extraction.zip)

**Comment by Clemens-Preisinger** [comment]
Thanks for the bug report. In Karamba3D 1.3.3 all load-cases - including eigen-, vibration- and buckling modes - were indexed by numbers. In version 2.0.0 load-cases are named using strings which has led to backward compatibility problems like the one you encountered. A quick work-around would be to use 'VibeMode_#0' to reference the first vibration mode (see attached file:
[eigenvector.extraction.zip](https://github.com/karamba3d/K3D_NightlyBuilds/files/5807463/eigenvector.extraction.zip)
).
In future releases of Karamba3D it is planned to have more flexibility with regards to handling load-cases so that results from natural vibration calculations can exist alongside results from external loads in the same model for e.g. doing spectral analysis. That's the reason for moving from indices to strings for referring to load-cases.
-- Clemens

**Comment by lucasepp** [comment]
Perfect - I figured it was something to do with the move from pure load cases to having result cases etc, but didn't know the format you had used for the load-case strings for natural vibrations.   Would perhaps be a good idea if the deconstruct model component or similar would spit out a list of resulting load cases for transparency to the user?  Or some other UI approach for showing this.
Thanks!
Lucas
