### ISSUE TITLE
BUG: Forces for Beam Elements with a Spring Cross Section

### ISSUE THREAD

**Issue by MCFormatEng** [karamba3d/K3D_NightlyBuilds#52]
**Describe the bug**
For the "Beam View" and "Beam Forces" components no forces are output for elements which have a spring cross section.

**To Reproduce**
1. Create a beam element from a line.
2. Assign a spring cross section using the "Cross Section" component.
3. Load the element
4. Analysis model
5. Look at the beam forces
6. See that all results are 0.0

**Notes**
[Karamba Spring Forces Error.zip](https://github.com/karamba3d/K3D_NightlyBuilds/files/8014052/Karamba.Spring.Forces.Error.zip)

**Comment by Clemens-Preisinger** [comment]
Thanks for your bug report. I will try to fix this as soon as possible.
--Clemens

**Comment by Clemens-Preisinger** [comment]
Dear @MCFormatEng,
I could not reproduce the bug. Did you use the latest build of Karamba3d from [here](https://github.com/karamba3d/K3D_NightlyBuilds/releases)?
The display of springs (see [here](https://manual.karamba3d.com/3-in-depth-component-reference/3.3-cross-section/3.3.3-spring-cross-sections)) is special: they show up as beam pieces of length 1 meter. The reason is to make it possible to deal with zero length springs.
-- Clemens

**Comment by MCFormatEng** [comment]
Hi @Clemens-Preisinger,

Sorry, you are correct, I hadn't updated to the latest build and doing so fixes the issue.

Thank you for you help,
Matt
